services:
  bot:
    container_name: bot_container
    image: hvichakardava/telegram_dream_analyst-bot:v2
#    build:
#      context: .
#      dockerfile: Dockerfile
    environment:
      - TELEGRAM_API_ID=21517623
      - TELEGRAM_API_HASH=91a7828d945f26c8e37227568e85147f
      - TELEGRAM_BOT_TOKEN=6823044772:AAFXI4yuQIwfU3rq2MF9xrj47MDwSWWw-CY
      - OPENCAGE_API_KEY=47f19b58763542309908925d4357927b
      - WEATHER_API_KEY=48390dd0b5cc12b9923ac4bc75063c85
      - WEATHER_BASE_URL=http://api.openweathermap.org/data/2.5/weather
      - DATABASESL_URL=sleep_data.db #sqlite:///Users/hvicakardava/PycharmProjects/telegram_dream_analyst/db/
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=pS$9!M6SMNWL@6<5
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=sleep_bot_database
    depends_on:
      - db
    volumes:
      - ./configs:/app/configs
      - ./db:/app/db
      - ./handlers:/app/handlers
    networks:
      - pgnetwork
    restart: always

  db:
    container_name: db_container
    image: postgres:14.12-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: sleep_bot_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pS$9!M6SMNWL@6<5
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d sleep_bot_database" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - pgnetwork

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "in-fo@inbox.ru" # Установите свой email
      PGADMIN_DEFAULT_PASSWORD: "admin" # Установите свой пароль
      PGADMIN_CONFIG_SERVER_MOD: "False"
    volumes:
      - ./data:/data
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - pgnetwork

volumes:
  db_data:
  pgadmin-data:


networks:
  pgnetwork:
    driver: bridge
